name: CI Validation

on: [push, pull_request]

jobs:
  validate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check script syntax
      run: |
        cd src
        echo Validating batch script...
        cmd /c "call Windows_Ultimate_Optimizer_0.7_BETA.bat /?"
